export const countryData = [
  { country: "United States", code: "us", flag: "us" },
  { country: "United Kingdom", code: "gb", flag: "gb" },
  { country: "India", code: "in", flag: "in" },
  { country: "Canada", code: "ca", flag: "ca" },
  { country: "Australia", code: "au", flag: "au" },
  { country: "Germany", code: "de", flag: "de" },
  { country: "France", code: "fr", flag: "fr" },
  { country: "Italy", code: "it", flag: "it" },
  { country: "Spain", code: "es", flag: "es" },
  { country: "Netherlands", code: "nl", flag: "nl" },
  { country: "Belgium", code: "be", flag: "be" },
  { country: "Switzerland", code: "ch", flag: "ch" },
  { country: "Sweden", code: "se", flag: "se" },
  { country: "Norway", code: "no", flag: "no" },
  { country: "Denmark", code: "dk", flag: "dk" },
  { country: "Finland", code: "fi", flag: "fi" },
  { country: "Ireland", code: "ie", flag: "ie" },
  { country: "Portugal", code: "pt", flag: "pt" },
  { country: "Austria", code: "at", flag: "at" },
  { country: "Poland", code: "pl", flag: "pl" },
  { country: "Czech Republic", code: "cz", flag: "cz" },
  { country: "Slovakia", code: "sk", flag: "sk" },
  { country: "Hungary", code: "hu", flag: "hu" },
  { country: "Romania", code: "ro", flag: "ro" },
  { country: "Bulgaria", code: "bg", flag: "bg" },
  { country: "Greece", code: "gr", flag: "gr" },
  { country: "Turkey", code: "tr", flag: "tr" },
  { country: "Russia", code: "ru", flag: "ru" },
  { country: "Ukraine", code: "ua", flag: "ua" },
  { country: "Japan", code: "jp", flag: "jp" },
  { country: "South Korea", code: "kr", flag: "kr" },
  { country: "China", code: "cn", flag: "cn" },
  { country: "Singapore", code: "sg", flag: "sg" },
  { country: "Malaysia", code: "my", flag: "my" },
  { country: "Thailand", code: "th", flag: "th" },
  { country: "Indonesia", code: "id", flag: "id" },
  { country: "Philippines", code: "ph", flag: "ph" },
  { country: "Vietnam", code: "vn", flag: "vn" },
  { country: "Pakistan", code: "pk", flag: "pk" },
  { country: "Sri Lanka", code: "lk", flag: "lk" },
  { country: "Nepal", code: "np", flag: "np" },
  { country: "United Arab Emirates", code: "ae", flag: "ae" },
  { country: "Saudi Arabia", code: "sa", flag: "sa" },
  { country: "Qatar", code: "qa", flag: "qa" },
  { country: "Israel", code: "il", flag: "il" },
  { country: "Egypt", code: "eg", flag: "eg" },
  { country: "South Africa", code: "za", flag: "za" },
  { country: "Nigeria", code: "ng", flag: "ng" },
  { country: "Kenya", code: "ke", flag: "ke" },
  { country: "Argentina", code: "ar", flag: "ar" },
  { country: "Brazil", code: "br", flag: "br" },
  { country: "Chile", code: "cl", flag: "cl" },
  { country: "Colombia", code: "co", flag: "co" },
  { country: "Mexico", code: "mx", flag: "mx" },
  { country: "Peru", code: "pe", flag: "pe" },
];
